Add note about new actions to example
DevExpress/testcafe-examples pull request #51
Opened 2021-04-01 08:04 UTC by DIRECTcut

2021-04-01 08:05 UTC, miherlosev approved these changes

2021-04-01 10:44 UTC, titerman requested changes

2021-04-01 10:44 UTC, titerman commented on examples/scroll/README.md
> +> UPDATE: TestCafe v1.14 release adds scroll actions to the test controller. There is no need to use client functions or `hover` to scroll the webpage. Read the documentation for details:
'version' and 'release' are synonymous

```suggestion
> UPDATE: TestCafe v1.14 includes dedicated scroll actions. You do not need to interact with off-screen elements, or execute client-side code to scroll the webpage. Read the documentation for details:
```

2021-04-01 15:24 UTC, titerman approved these changes

2021-04-01 17:17 UTC, arminal commented on examples/scroll/README.md
> +> UPDATE: TestCafe v1.14 includes dedicated scroll actions. You do not need to interact with off-screen elements, or execute client-side code to scroll the webpage. Read the documentation for details
```suggestion
> UPDATE: TestCafe v1.14 includes dedicated scroll actions. You do not need to interact with off-screen elements or execute client-side code to scroll the webpage. Read the documentation for details:
```

2021-04-01 17:17 UTC, arminal commented on examples/scroll/README.md
>  The test page has two buttons. They are located at 2000 px and 4000 px along the X-axis, respectively (both outside of the viewport).
```suggestion
The test page has two buttons. They are located at 2000 px and 4000 px along the X-axis, respectively (outside of the viewport).
```

2021-04-01 17:19 UTC, arminal reviewed
| `y`  | the number of pixels by which the page is scrolled vertically.|
there should be no period here

2021-04-02 14:15 UTC, arminal commented on examples/scroll/README.md
> +The test page has two buttons. They are located at 2000 px and 4000 px along the X-axis, respectively (outside of the viewport).
```suggestion
The test page has two buttons. They are located at 2000 px and 4000 px along the X-axis (outside of the viewport), respectively.
```

2021-04-07 15:26 UTC, merged