Add the "Multiuser scenario" example
DevExpress/testcafe-examples pull request #57
Opened 2021-04-30 14:01 UTC by AndreyBelym

Originally created by @felis2803. Unfortunately, I force-pushed some inappropriate commits (that wasn't connected to this repo, only to the [standalone example repo](https://github.com/DevExpress/testcafe-example-multiuser-scenario)) to his pull request, and it was closed automatically by GitHub, and it seems now I cannot commit anymore there.

I guess we still have to rewrite README according to the [template](https://github.com/DevExpress/testcafe-examples/pull/32).

2021-04-30 15:03 UTC, felis2803 approved these changes

2021-05-04 16:42 UTC, titerman requested changes

2021-05-04 16:42 UTC, titerman commented on detached-examples/multiuser-scenario/README.md
> +This example shows you how to start two TestCafe Runners and synchorize them to achieve testing with two different users in different browsers
```suggestion
You can not sign multiple users into the same website with a single instance of TestCafe. The solution to this limitation is to run multiple instances of TestCafe. This example shows you how to run multi-user tests with two or more synchronized TestCafe Runners.
```

2021-05-04 16:47 UTC, titerman approved these changes

2021-05-06 15:37 UTC, merged

2021-05-07 11:36 UTC, miherlosev commented
It's necessary adding this example link to the [main page](https://github.com/DevExpress/testcafe-examples#examples-in-this-repository) and the [documentation](https://testcafe.io/documentation/402637/examples) site.

I don't remember our decision about the location of the documentation issues.
Should we write an appropriate issue on GitHub or GitLab?
@AndreyBelym  @titerman

2021-05-07 11:38 UTC, titerman commented
I still use GitHub to keep track of documentation-related issues, and plan on doing so going forward. Feel free to add an issue to the main TestCafe repo

2021-05-07 11:59 UTC, miherlosev commented
Done - https://github.com/DevExpress/testcafe/issues/6213